### PR TITLE
downgrade one https url to http to trigger mcb [#1414776]

### PR DESCRIPTION
**Pull request by floatingatoll**
I accidentally upgraded one https:// to http:// when doing these changes for Henrik, this undoes that.

### CODE REVIEW

**Review by whimboo — APPROVED** [review]
And I didn't notice that. Thank you for the fix-up!

**Comment by whimboo** [comment]
@april can you please merge? Thank you.

**Comment by april** [comment]
Would you like me to make you an admin on the repository? It makes sense that you could approve merges.

**Comment by whimboo** [comment]
I don't think that I have to approve/merge commits in the future. So I'm fine without for now. But thank you anyway.

**Pull request merged**
